---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    branches: ["main"]
    paths: ["functions/**"]
  workflow_dispatch:
    inputs:
      function:
        type: string
        description: Function Name
        required: true
      release:
        type: boolean
        description: Release
        required: false
        default: false

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get Changed Files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@1a5aeab1bfa64d0c4e786f501d5a3f1fad4a24da # v0.4.1
        with:
          path: functions
          include_only_directories: true
          max_depth: 1

  changed:
    if: ${{ needs.prepare.outputs.changed-files != '[]' || github.event_name == 'workflow_dispatch' }}
    needs: ["prepare"]
    name: Get Changed Functions
    runs-on: ubuntu-latest
    outputs:
      functions: ${{ steps.functions.outputs.functions }}
    steps:
      - name: Get Functions
        id: functions
        run: |
          if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
            echo 'functions=["${{ inputs.function }}"]' >> $GITHUB_OUTPUT
          else
            CHANGED="${{ needs.prepare.outputs.changed-files }}"
            if [ "$CHANGED" != "[]" ]; then
              echo "functions=$CHANGED" >> $GITHUB_OUTPUT
            else
              echo "functions=[]" >> $GITHUB_OUTPUT
            fi
          fi

  build:
    if: ${{ needs.changed.outputs.functions != '[]' }}
    needs: ["changed"]
    name: Build ${{ matrix.function }}
    uses: ./.github/workflows/function-builder.yaml
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    strategy:
      matrix:
        function: ${{ fromJSON(needs.changed.outputs.functions) }}
      fail-fast: false
      max-parallel: 4
    with:
      function: ${{ matrix.function }}
      release: ${{ github.event_name == 'workflow_dispatch' && inputs.release || github.event_name == 'push' }}

  status:
    if: ${{ !cancelled() }}
    needs: ["build"]
    name: Build Success
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
